{% set name = "fs-gcsfs" %}
{% set version = "1.3.0" %}
{% set sha256 = "cdafa407b27de694a83451efbcd20417ded6d35371fd30b587b4e35d4399de9b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - google-cloud-storage >=1.10.0,<2
    - fs >=2.0.0,<3

test:
  imports:
    - fs_gcsfs

about:
  home: https://github.com/Othoz/gcsfs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python filesystem abstraction of Google Cloud Storage (GCS) implemented as a PyFilesystem2 extension
  doc_url: https://fs-gcsfs.readthedocs.io/
  dev_url: https://github.com/Othoz/gcsfs

extra:
  recipe-maintainers:
    - birnbaum
    - mathiaseitz
    - trendelkampschroer
