{% set name = "fs-gcsfs" %}
{% set version = "1.4.5" %}
{% set sha256 = "44b615e4fcbf27d770cce83664fed8c6930501ce949d8be80ab42c4f0806aa9c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - fs >=2,<3
    - google-cloud-storage >=1.10,<2
    - urllib3 >=1.25,<2
    - packaging >=20,<21
    - requests >=2.20,<3

test:
  imports:
    - fs_gcsfs

about:
  home: https://github.com/Othoz/gcsfs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python filesystem abstraction of Google Cloud Storage (GCS) implemented as a PyFilesystem2 extension
  doc_url: https://fs-gcsfs.readthedocs.io/
  dev_url: https://github.com/Othoz/gcsfs

extra:
  recipe-maintainers:
    - mathiaseitz
    - trendelkampschroer
