travis:
  secure:
    BINSTAR_TOKEN: ka+AdwEV7PlssXFSZI1Ke4muEFBiPCDAYhAIGuBxtcmI0lMD5dj+2zw4oU5RTVVTZkPfkIWN2JVas+9bcXxTLkj4drgI89eEwdndi4I6gyXJeTEqHaso00c5HjqhAycZnwm9sVxa5dl2b6+MJt9zywdyXk6x536ghlXBXwNrDlvWObAGESOg3w1TuYk+3Nrkx2rJgOh0bhAQWJ5/+28o1MMLSbt3H3WBCuLwMjbg4rGzrcjkAcVZU7EESSEeEZXLPylL661AOgJVEq2Fuuzry+km/sZZjMi/n4rOSG2P53e9V7HCD7GGdGZLigWFo5GSxupcxUIphCBFkGfLNqbU6ju5HHU0gFKmTnVHIdbtQVXsQI/Zf4rWhj7KDEmQ8ZVxj5RJgiWsuVkUM/tfl0xYoFkfLrZniSVPLbcusQps/WCFC/S/Cb5/na9gILB/1pdMCy8g9AweMZaTj3yY/aSNIhGt5W/gXDVnTkJXQs72xyIQQzWfub0mcoXLaykQUR9NAZ5F8AQB/26NjqCMgk8cQpmPK0LtCUkWZGXIlYbWvhyrvTBbCwZrdZSnH3mPSnXrI6VwywzXfFn167+ZOj2dms2clgmIGwaP4NiTH4VvO5ShBYywJMZLkNC61/VhjvhYWxcmDOHgqnZSIPvVjIqc6PdQPS1mv3VTbJuw0r0YX5g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
